input {
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/logstash-core/lib/jars/postgresql-42.7.3.jar"
    jdbc_driver_class => "org.postgresql.Driver"
    jdbc_connection_string => "jdbc:postgresql://db:5432/OUDocumentHub_db"
    jdbc_user => "documenthub_db"
    jdbc_password => "1234567890"
    schedule => "*/30 * * * *"
statement => "SELECT cru.room_id, cru.user_id, u.first_name AS user_first_name, u.last_name AS user_last_name, (SELECT first_name || ' ' || last_name FROM users WHERE user_id != cru.user_id AND user_id IN (SELECT user_id FROM chat_rooms_users WHERE room_id = cru.room_id LIMIT 1)) AS other_user_name, cru.last_message_read, (SELECT created_at FROM messages WHERE message_id = cru.last_message_read) AS last_message_read_time FROM chat_rooms_users cru JOIN users u ON cru.user_id = u.user_id"
    type => "chat_rooms_users"
    jdbc_fetch_size => 1000
  }

  jdbc {
    jdbc_driver_library => "/usr/share/logstash/logstash-core/lib/jars/postgresql-42.7.3.jar"
    jdbc_driver_class => "org.postgresql.Driver"
    jdbc_connection_string => "jdbc:postgresql://db:5432/OUDocumentHub_db"
    jdbc_user => "documenthub_db"
    jdbc_password => "1234567890"
    schedule => "*/30 * * * *"
    statement => "
      SELECT m.message_id, m.is_edit, m.is_delete, m.sender, m.room_id, m.reply_id, 
             m.content, m.created_at, m.updated_at, 
             COALESCE(u.first_name || ' ' || u.last_name, 'Unknown') AS sender_name,
             u.first_name AS sender_first_name, u.last_name AS sender_last_name, u.email AS sender_email
      FROM messages m
      LEFT JOIN users u ON m.sender = u.user_id
      WHERE m.updated_at > :sql_last_value OR m.created_at > :sql_last_value
    "
    use_column_value => true
    tracking_column => "updated_at"
    tracking_column_type => "timestamp"
    last_run_metadata_path => "/usr/share/logstash/.logstash_jdbc_last_run_messages"
    clean_run => false
    type => "messages"
    jdbc_fetch_size => 1000
  }
}

filter {
  if [type] == "chat_rooms_users" {
    mutate {
      add_field => { "[@metadata][document_id]" => "%{room_id}-%{user_id}" }
      add_field => { "other_user_name" => "%{user_first_name} %{user_last_name}" }
      convert => { 
        "room_id" => "string"
        "user_id" => "string"
        "last_message_read" => "string"
        "user_first_name" => "string"
        "user_last_name" => "string"
        "user_email" => "string"
        "other_user_name" => "string"
      }
      if [last_message_read_time] {
      date {
        target => "last_message_read_time"
      }
  }
      remove_field => ["@version"]
    }
  }

  if [type] == "messages" {
    mutate {
      convert => { 
        "message_id" => "string"
        "sender" => "string"
        "room_id" => "string"
        "reply_id" => "string"
        "sender_first_name" => "string"
        "sender_last_name" => "string"
        "sender_email" => "string"
      }
      rename => { 
        "message_id" => "id"
        "content" => "message_text"
        "sender" => "sender_id"
        "room_id" => "chat_room_id"
      }
      remove_field => ["@version", "updated_at"]
      add_field => { "[@metadata][document_id]" => "%{id}" }
    }
    date {
      target => "created_at"
      remove_field => ["debug_created_at"]
    }
  }
}

output {
  if [type] == "chat_rooms_users" {
    elasticsearch {
      hosts => ["http://host.docker.internal:9200"]
      index => "chat_rooms_users"
      document_id => "%{[@metadata][document_id]}"
      user => "elastic"
      password => "${ELASTIC_PASSWORD}"
    }
  }

  if [type] == "messages" {
    elasticsearch {
      hosts => ["http://host.docker.internal:9200"]
      index => "messages"
      document_id => "%{[@metadata][document_id]}"
      user => "elastic"
      password => "${ELASTIC_PASSWORD}"
    }
  }

  stdout { codec => rubydebug }
}
