input {
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/logstash-core/lib/jars/postgresql-42.7.3.jar"
    jdbc_driver_class => "org.postgresql.Driver"
    jdbc_connection_string => "jdbc:postgresql://db:5432/OUDocumentHub_db"
    jdbc_user => "documenthub_db"
    jdbc_password => "1234567890"
    schedule => "*/5 * * * *"
    statement => "
      SELECT 
        o.order_id,
        o.status,
        o.payment_method,
        o.created_at,
        o.created_by,
        o.customer_last_name,
        o.customer_first_name,
        o.customer_phone_number,
        o.customer_email,
        json_agg(
          DISTINCT json_build_object(
            'item_id', oi.item_id,
            'document_id', oi.document_id,
            'quantity', oi.quantity,
            'status', oi.status
          )
        ) AS order_items
      FROM orders o
      LEFT JOIN order_items oi ON o.order_id = oi.order_id
      GROUP BY o.order_id
    "
    clean_run => true
  }
}

filter {
  mutate {
    copy => { "order_id" => "[@metadata][document_id]" }
    rename => {
      "customer_last_name" => "[customer][last_name]"
      "customer_first_name" => "[customer][first_name]"
      "customer_phone_number" => "[customer][phone_number]"
      "customer_email" => "[customer][email]"
    }
    remove_field => ["@version"]
  }

  json {
    source => "order_items"
    target => "order_items"
  }
}

output {
  elasticsearch {
    hosts => ["http://host.docker.internal:9200"]
    index => "orders"
    document_id => "%{[@metadata][document_id]}"
    user => "elastic"
    password => "${ELASTIC_PASSWORD}"
  }
  
  stdout { codec => rubydebug }
}

