# Logstash configuration to sync users table from PostgreSQL to Elasticsearch
# Performs incremental sync based on updated_at or created_at

input {
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/logstash-core/lib/jars/postgresql-42.7.3.jar"
    jdbc_driver_class => "org.postgresql.Driver"
    jdbc_connection_string => "jdbc:postgresql://db:5432/OUDocumentHub_db"
    jdbc_user => "documenthub_db"
    jdbc_password => "1234567890"
    schedule => "*/5 * * * *" # Run every 5 seconds
    statement => "
      SELECT 
        u.user_id, u.email, u.created_at, u.updated_at, u.last_name, u.first_name, 
        u.gender, u.avatar_link, u.is_banned, u.is_enable, u.date_of_birth, u.provider,
        si.merchant_id, si.is_verified, si.account_type, si.created_at AS si_created_at, si.updated_at AS si_updated_at,
        ARRAY_AGG(r.role_name) AS roles
      FROM users u
      LEFT JOIN seller_information si ON u.user_id = si.user_id
      LEFT JOIN user_role ur ON u.user_id = ur.user_id
      LEFT JOIN roles r ON ur.role_id = r.role_id
      WHERE u.updated_at > :sql_last_value OR u.created_at > :sql_last_value
      GROUP BY u.user_id, si.user_id
    "
    use_column_value => true
    tracking_column => "updated_at"
    tracking_column_type => "timestamp"
    last_run_metadata_path => "/usr/share/logstash/.logstash_jdbc_last_run_users"
    clean_run => false # Incremental sync
  }
}

filter {
    mutate {
      copy => { "user_id" => "[@metadata][document_id]" }
      convert => {
        "user_id" => "string"
        "is_banned" => "boolean"
        "is_enable" => "boolean"
        "is_verified" => "boolean"
      }
      remove_field => ["@version", "updated_at", "si_updated_at"]
    }
}

output {
    elasticsearch {
      hosts => ["http://host.docker.internal:9200"]
      index => "users"
      document_id => "%{[@metadata][document_id]}"
      user => "elastic"
      password => "${ELASTIC_PASSWORD}"
    }
  stdout { codec => rubydebug } # For debugging
}
