stages:
  - build
  - test

include:
  - gitlab-templates/base-line.yml

.backend:
  extends: 
    - .base-line

build-job:
  stage: build
  extends: 
    - .backend
  script:
    - echo "build phase"

test-job:
  stage: test
  extends: 
    - .backend
  script:
    - echo "test phase"
