spring:
  application:
    name: backend

  datasource:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: none
    defer-datasource-initialization: ${IS_INITDB}

  sql:
    init:
      schema-locations: classpath:/schema.sql
      mode: ${IS_RUNDB_SCRIPT}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope:
              - openid
              - profile
              - email
              - https://www.googleapis.com/auth/user.birthday.read
              - https://www.googleapis.com/auth/user.gender.read
          facebook:
            client-id: ${FACEBOOK_CLIENTID}
            client-secret: ${FACEBOOK_CLIENTSECRET}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org:
      springframework:
        security: DEBUG

#app variable
aws:
  s3:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}
    bucket-name: ${AWS_BUCKET_NAME}
    enabled: true

frontend:
  url: ${FRONTEND_URL}

access-token:
  private: ./access-refresh-token-keys/access-token-private.key
  public: ./access-refresh-token-keys/access-token-public.key

refresh-token:
  private: ./access-refresh-token-keys/refresh-token-private.key
  public: ./access-refresh-token-keys/refresh-token-public.key

api-route: api/v1
